---
title: "Commune Analysis"
author: "Dave Kennedy"
date: "24/02/2022"
output:
  html_document: 
  keep_md: yes
---

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.asp = 0.8,
	fig.height = 12,
	fig.retina = 2,
	fig.width = 12,
	include=FALSE,
	warning = FALSE,
	cache = TRUE,
	dev = "jpeg",
	dpi = 600,
	units="cm",
	include = FALSE,
	out.width = "100%"
)
require(pacman)
library(tidyverse)
pacman::p_load(raster, sf, exactextractr, here,
               readxl, tidyxl, unpivotr,
               leaflet, leaflet.extras, 
               janitor, patchwork,RColorBrewer,
               ggsflabel,broom,kableExtra,ggthemes,
               ggsn,gghighlight,ggsflabel,ggbeeswarm,
               data.table,linelist,tidylog, patchwork,gt)

commune_palette <- colorRampPalette(rev(brewer.pal(6, "Spectral")))
commune_fill <- scale_fill_stepsn(n.breaks = 6, colours = viridis::viridis(6), limits=c(1, 100))
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colours = myPalette(100), limits=c(0, 1))

```

```{r data-wrangling}
# Import shapefiles 
iu_shp <-
  read_sf(here('data', 'input', 'shp', 'ESPEN_IU_2020.shp')) %>%
  filter(ADMIN0 == 'Angola') %>% 
  select(IU_ID,ADMIN1, ADMIN2, geometry)

# 164 implementation units

commune_shp <- read_sf(here('data', 'input', 'shp', 'ago_admbnda_adm3_gadm_ine_ocha_20180904.shp')) %>% 
  select(ADM1_EN, ADM1_PCODE, ADM2_EN,ADM2_PCODE, ADM3_EN,ADM3_PCODE, geometry) %>% 
    clean_data()

adm1_shp <- commune_shp %>%
  group_by(adm1_en) %>%
  summarise()


# 539 communes 


# 18 provinces 

source(here('scripts', 'admin_db.R'))

commune_shp_linked <- commune_shp %>% 
  inner_join(final_linked_db %>% 
              select('adm1_pcode', 'adm2_pcode', 'adm3_pcode','iu_id', 'total_pop'),
            by=c('adm1_pcode', 'adm2_pcode', 'adm3_pcode')) %>% 
                 distinct(adm1_pcode, adm2_pcode, adm3_pcode, .keep_all=TRUE)

x <- commune_shp_linked %>% as_tibble() %>% select(-geometry)

write.csv(x, here('data', 'output', 'commune_pop.csv'))

# Import oncho data from ESPEN
oncho_wd <-
  read.csv(here('data', 'input', 'espen_platform_oncho.csv')) %>%
  filter(Year == 2020) %>% 
  select(IU_ID, Endemicity, population=PopTot) 

oncho_cat_table <- oncho_wd %>% tabyl(Endemicity) %>%  
  gt(rowname_col = "Endemicity") %>% 
  tab_header(
    title = "Onchocerciasis endemicity categories",
    subtitle = "Data from ESPEN data portal") %>% 
  fmt_percent(
    columns = percent,
    decimals = 0
  )

saveRDS(oncho_cat_table, here('tables', 'oncho_cat_table.Rds'))



# 164 IUs

loa_loa_wd <-
  read.csv(here('data', 'input', 'espen_platform_loaloa.csv')) %>% 
  filter(Year==2020) %>% 
  select(IU_ID, loaloa_status=Endemicity)
# 164 IUs
iu_loaloa_endemicity_tbl <- loa_loa_wd %>% tabyl(loaloa_status)

lf_wd <- read.csv(here('data', 'input', 'espen_platform_lf.csv')) %>% 
    filter(Year==2020) %>% 
  select(IU_ID, lf_status=Endemicity)

iu_lf_endemicity_tbl <- lf_wd %>% tabyl(lf_status)


oncho_loa_loa_lf_data <- oncho_wd %>% 
    left_join(loa_loa_wd, by=c('IU_ID')) %>% 
      left_join(lf_wd, by=c('IU_ID')) 

iu_loaloa_endemicity_tbl <- oncho_loa_loa_lf_data %>%   
  filter(grepl('Unknown', Endemicity)) %>% mutate(endemicity_upd="Unknown") %>% 
  tabyl(endemicity_upd, loaloa_status) %>% 
     # adorn_totals(c("row", "col")) %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(rounding = "half up", digits = 0) %>% 
    adorn_ns()

saveRDS(iu_loaloa_endemicity_tbl, here('tables', 'iu_loaloa_endemicity_tbl.Rds'))

iu_lf_endemicity_tbl <- oncho_loa_loa_lf_data %>%   
  filter(grepl('Unknown', Endemicity)) %>% mutate(endemicity_upd="Unknown") %>% 
  tabyl(endemicity_upd, lf_status) %>% 
     # adorn_totals(c("row", "col")) %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(rounding = "half up", digits = 0) %>% 
    adorn_ns()


saveRDS(iu_lf_endemicity_tbl, here('tables', 'iu_lf_endemicity_tbl.Rds'))


unknown_commune_shp <- commune_shp_linked %>% 
    left_join(oncho_loa_loa_lf_data, by=c('iu_id' = 'IU_ID')) %>% 
  #left_join(oncho_wd, by=c('iu_id' = 'IU_ID')) %>% 
  filter(grepl('Unknown', Endemicity)) 
  #select(-Endemicity) %>% 
  #left_join(loa_loa_wd, by=c('iu_id' = 'IU_ID')) 
  #mutate(oncho_status="Unknown")
  
# unknown_commune_shp %>% 
#   as_tibble() %>%
#   #filter(loaloa_status=="Non-endemic") %>% 
#     tabyl(Endemicity,lf_status) %>%
#     adorn_totals(c("row", "col")) %>%
#   adorn_percentages("row") %>%
#   adorn_pct_formatting(rounding = "half up", digits = 0) %>%
#   adorn_ns() %>%
#   adorn_title("combined")

commune_oncho_endemicity_tbl <- commune_shp_linked %>% as_tibble() %>% 
  left_join(oncho_loa_loa_lf_data, by=c('iu_id' = 'IU_ID')) %>% 
  tabyl(Endemicity) %>% 
  adorn_pct_formatting(rounding = "half up", digits = 0) %>% 
  adorn_totals("row")

saveRDS(commune_oncho_endemicity_tbl, here('tables', 'commune_oncho_endemicity_tbl.Rds'))
  
commune_oncho_loaloa_endemicity_tbl <- commune_shp_linked %>% as_tibble() %>% 
  left_join(oncho_loa_loa_lf_data, by=c('iu_id' = 'IU_ID')) %>% 
  filter(grepl("unknown", Endemicity, ignore.case=TRUE)) %>% 
  tabyl(Endemicity, loaloa_status) %>% 
  adorn_totals(c( "col", "row")) %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 0) %>%
  adorn_ns()
  
saveRDS(commune_oncho_loaloa_endemicity_tbl, here('tables', 'commune_oncho_loaloa_endemicity_tbl.Rds'))
  
commune_oncho_lf_endemicity_tbl <- commune_shp_linked %>% as_tibble() %>% 
  left_join(oncho_loa_loa_lf_data, by=c('iu_id' = 'IU_ID')) %>% 
  filter(grepl("unknown", Endemicity, ignore.case=TRUE)) %>% 
  tabyl(Endemicity, lf_status) %>% 
  adorn_totals(c( "col", "row")) %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 0) %>%
  adorn_ns()
  
saveRDS(commune_oncho_lf_endemicity_tbl, here('tables', 'commune_oncho_lf_endemicity_tbl.Rds'))
  


```

```{r map-angola-commune}
# Map to check data
iu_commune_map_labels <- adm1_shp %>%
  ggplot() +
  geom_sf(fill = "transparent", color = "black", size = 1.5) +
  geom_sf_label(aes(label = adm1_en)) +
  theme_minimal()

iu_commune_map_labels

commune_map <- commune_shp %>%
  ggplot() +
  geom_sf(fill = "transparent", color = "red", size = 0.5) +
     geom_sf(fill = "transparent", color = "black", size = 1.5,
            data=adm1_shp) +
    theme_minimal()

commune_map

endemicity_labels <- oncho_wd %>% tabyl(Endemicity) %>% pull(Endemicity)

scale_fill_end <- function(...){
    ggplot2:::manual_scale(
        'fill', 
        values = setNames(c('green', 'blue', 'red', 'orange'), 
                          endemicity_labels), 
        ...
    )
}

iu_commune_endemicity <- iu_shp %>% 
  left_join(oncho_wd, by='IU_ID') %>% 
  ggplot() +
  geom_sf(aes(fill = Endemicity),
    size = 0.05) +
        geom_sf(fill = "transparent", color = "black", size = 1.5,
            data=adm1_shp) +
  labs(fill="Oncohcerciasis Endemicity") +
        theme(legend.position = c(0.85, 0.9)) +
  scale_fill_end() +
    theme_minimal() 


iu_commune_endemicity

iu_commune_map <- unknown_commune_shp %>%
  ggplot() +
  geom_sf(aes(fill = Endemicity)) +
    geom_sf(fill = "transparent", color = "black", size = 1.5,
            data=adm1_shp) +
  labs(fill="Oncohcerciasis Endemicity") +
        theme(legend.position = c(0.85, 0.9)) +
    scale_fill_end() +
    theme_minimal() 

iu_commune_map

```
```{r neighbour-polygons}

# Want to identify communes neighbouring endemic communes

polygon_endemicity_shp <- commune_shp_linked %>% 
    left_join(oncho_loa_loa_lf_data, by=c('iu_id' = 'IU_ID')) %>% 
  mutate(endemicity_bin=case_when(grepl('Endemic', Endemicity) ~ 'Endemic',
                              TRUE ~ "Unknown")) %>% 
  select(adm1_en, adm2_en, adm3_en, endemicity_bin, geometry) %>% 
    mutate(polygon_id = row_number())


neighbors <- st_touches(polygon_endemicity_shp) %>% 
  as.data.frame() %>% 
  select(polygon_id=row.id, neighbour_polygon_id=col.id) %>% 
  group_by(polygon_id) %>% 
  mutate(neighbour_count = paste('poly_neighbour', dplyr::row_number(), sep='_')) %>% 
  pivot_wider(names_from=neighbour_count, values_from=neighbour_polygon_id)
  

polygon_endemicity_neighbours_shp <- polygon_endemicity_shp %>% 
  left_join(neighbors, by='polygon_id')

endemic_poly <- polygon_endemicity_neighbours_shp %>% filter(grepl('Endemic', endemicity_bin)) %>% pull(polygon_id)
  
endemic_neighbour <- polygon_endemicity_neighbours_shp %>% filter(grepl('Endemic', endemicity_bin)) %>% 
  as_tibble() %>% 
  select(polygon_id, starts_with('poly_neighbour')) %>% 
  pivot_longer(-polygon_id) %>% 
  filter(!is.na(value)) %>% 
  distinct(value) %>% 
  arrange(value) %>% 
  pull(value)

endemic_neighbour_filtered <- setdiff(endemic_neighbour, endemic_poly)

#Need to filter endemic neighbour on endemic poly
neighbour_endemic_area <- polygon_endemicity_shp %>% 
  filter(polygon_id %in% endemic_neighbour_filtered) %>% 
  select(-c(polygon_id, geometry))

neighbour_endemic_area_map <- neighbour_endemic_area %>% 
  ggplot() +
  geom_sf(aes(fill = endemicity_bin),
    size = 0.05) +
        geom_sf(fill = "transparent", color = "black", size = 1.5,
            data=adm1_shp) +
  labs(fill="Oncohcerciasis Endemicity") +
        theme(legend.position = c(0.85, 0.9)) +
    theme_minimal() 

neighbour_endemic_area_map


```

```{r raster-wrangling}

#Import environmental suitability as raster data
africa_oncho_rs <-
  stack(here('data', 'IHME_AFRICA_ONCHO_ENV_SUIT_MEAN_Y2020M08D26.TIF'))

#Crop raster to shapefile of communes within IUs with unknown endemicity
unknown_iu_oncho_combined <-
  exact_extract(africa_oncho_rs,
                unknown_commune_shp,
                progress = FALSE)  %>%
  bind_rows(., .id = "id") %>%
  as_tibble() %>% 
  mutate(id = as.numeric(id)) %>%
  #--- group summary ---#
  filter(!is.na(value))

# Merge raster values with shapefile
angola_commune_oncho <- unknown_commune_shp %>%
  mutate(id := seq_len(nrow(.))) %>%
  left_join(., unknown_iu_oncho_combined, by = "id") 

# Import raster data in raster format
library(raster)
africa_oncho_raster <- raster::raster(here('data', 'IHME_AFRICA_ONCHO_ENV_SUIT_MEAN_Y2020M08D26.TIF'))

angola_oncho_raster_crop <- mask(africa_oncho_raster, iu_shp)
angola_oncho_raster_crop <- crop(angola_oncho_raster_crop, iu_shp)

angola_oncho_point  <-  rasterToPoints(angola_oncho_raster_crop)
angola_oncho_point_df <-  data.frame(angola_oncho_point)
colnames(angola_oncho_point_df) = c("lon", "lat", "suitability")

ang_raster_map <- ggplot() +
  geom_sf() +
  geom_raster(data = angola_oncho_point_df, aes(lon, lat, fill = suitability/100), alpha = .7) +
  geom_sf(fill = "transparent", color = "black", size = 1.5, 
          data = adm1_shp) +
  labs(fill='Environmental suitability', x='', y='') +
  theme(legend.position='top') +
  theme_minimal() +
  sc 

ang_raster_map

rm(ang_raster_map,angola_oncho_raster_crop)

```

```{r}
#Calculate weighted mean
# angola_commune_oncho_collapse <- angola_commune_oncho %>%
#   group_by(adm1_en, adm2_en, adm3_en) %>%
#   summarise(oncho_mean_aw = sum(value * coverage_fraction) / sum(coverage_fraction))  

angola_commune_oncho_collapse <- setDT(angola_commune_oncho)[, keyby = .(adm1_en, adm2_en, adm3_en), 
                          .(oncho_mean_aw = sum(value * coverage_fraction) / sum(coverage_fraction))] %>%  
  merge(unknown_commune_shp, all=TRUE, by = c('adm1_en', 'adm2_en','adm3_en')) %>% 
  st_as_sf()

# y <- merge(unknown_commune_shp, angola_commune_oncho_collapse, all = TRUE, by = "Id")
# 
# angola_commune_oncho_collapse <- merge(unknown_commune_shp, angola_commune_oncho_summary, all.x = TRUE, by = c('adm1_en', 'adm2_en','adm3_en'))

# Map weighted mean by ADM3  
angola_commune_oncho_noloaloa_map <- angola_commune_oncho_collapse %>% 
  ggplot() +
  geom_sf(aes(fill = oncho_mean_aw)) +
     geom_sf(fill = "transparent", color = "black", size = 1.5,
          data = adm1_shp) +
  labs(fill="Environmental suitability (Mean)") +
    theme_minimal() +
  theme(legend.position = "top") +
  commune_fill

angola_commune_oncho_noloaloa_map
```



Check environmental suitability by Loa loa endemicity

```{r loa-loa}

(oncho_env_loaloa_compare <- ggplot(data=angola_commune_oncho %>% filter(grepl("Unknown", Endemicity)), 
                                    aes(x=value, group=loaloa_status, fill=loaloa_status)) +
    geom_density(adjust=1.5, alpha=.4) +
    labs(x="Environmental suitability", fill="Loa loa status"))
  
#oncho_env_loaloa_compare
 (oncho_env_loaloa_ttest <- t.test(value ~ loaloa_status, 
                                   data = angola_commune_oncho %>% filter(grepl("Unknown", Endemicity)), 
                                   var.equal = TRUE) %>% 
    tidy())
  
```

```{r env-suit-threshold}
angola_commune_oncho_noloaloa_over71<- setDT(angola_commune_oncho)[
  loaloa_status == "Non-endemic"] %>%  
  mutate(over71=case_when(value>=71 ~ 1, 
                          TRUE ~ 0)) %>% 
  count(adm1_en, adm2_en, adm3_en,over71) %>% 
  group_by(adm1_en, adm2_en, adm3_en) %>% 
  mutate(propover71=100*(n/sum(n))) %>% 
  filter(over71==1) %>% 
  #summarise(total_over71=sum(over71)) %>% 
  merge(unknown_commune_shp, by = c('adm1_en', 'adm2_en','adm3_en')) %>% 
  st_as_sf()

commune_mapping_filter <- readRDS(here('data', 'output', 'commune_mapping_filter.Rds')) %>% 
  mutate(prev_mapping=1)

angola_commune_oncho_noloaloa_over71 %>% left_join(commune_mapping_filter, by=c('adm2_pcode', 'adm3_pcode'))

angola_commune_oncho_noloaloa_over71_map <- angola_commune_oncho_noloaloa_over71 %>% 
  ggplot() +
  geom_sf(aes(fill = propover71)) +
     geom_sf(fill = "transparent", color = "black", size = 1.5,
          data = adm1_shp) +
     labs(fill="% of pixels (5x5km) in a commune exceeding environmental threshold >=0.71") +
    theme_minimal() +
  theme(legend.position = "top") +
    scale_fill_viridis_c(option = "magma", begin=0, end=1)

angola_commune_oncho_noloaloa_over71_map

```


```{r country-commune-noloaloa-map}
#Calculate weighted mean
angola_commune_oncho_noloaloa_collapse <- setDT(angola_commune_oncho)[
  loaloa_status == "Non-endemic"] [
  , keyby = .(adm1_en, adm2_en, adm3_en), 
                          .(oncho_mean_aw = sum(value * coverage_fraction) / sum(coverage_fraction))] %>%  
  merge(unknown_commune_shp, by = c('adm1_en', 'adm2_en','adm3_en')) %>% 
  st_as_sf() 

# Map weighted mean by ADM3  
(angola_commune_oncho_noloaloa_map <- angola_commune_oncho_noloaloa_collapse %>% 
  ggplot() +
  geom_sf(aes(fill = oncho_mean_aw)) +
     geom_sf(fill = "transparent", color = "black", size = 1.5, 
          data = adm1_shp) +
     labs(fill="Environmental suitability (Mean)") +
    theme_minimal() +
  theme(legend.position = "top") +
  commune_fill)

commune_boxwhisker <- angola_commune_oncho %>% 
  filter(loaloa_status == "Non-endemic") %>% 
  mutate(location_name=paste(adm1_en,adm2_en, sep= "-")) %>% 
  split(.$location_name) %>%
  imap(~ ggplot(data=.x) +
        geom_boxplot(aes(value, reorder(adm3_en,desc(adm3_en)))) + 
        theme_bw() +
        scale_x_continuous(limits=c(0,100),sec.axis = dup_axis()) +
        labs(x='Environmental suitability', 
             y='Commune') +
          ggtitle(.y) 
  )


commune_map <-  angola_commune_oncho_noloaloa_collapse %>%
  as.data.frame() %>% 
  st_as_sf() %>% 
  mutate(location_name=paste(adm1_en,adm2_en, sep= "-")) %>% 
  split(.$location_name) %>%
  imap(~ ggplot(data = .x) +
      geom_sf(aes(fill = oncho_mean_aw)) +
      geom_sf_label_repel(aes(label = adm3_en)) +
        labs(fill="Environmental suitability (Mean)") +
      theme(legend.position = 'top') +
      labs(x = "", y = "", fill = "Environmental suitability") +
      commune_fill +
      ggtitle(.y)
  )

commune_col <- angola_commune_oncho_noloaloa_collapse %>% 
  as_tibble() %>% 
  mutate(location_name=paste(adm1_en,adm2_en, sep= "-")) %>% 
  split(.$location_name) %>%
  imap(~ ggplot(data=.x) +
         geom_col(aes(x=adm3_en, y=total_pop)) +
       theme_bw() +
  scale_y_continuous(labels = scales::unit_format(unit = "K", scale = 1e-3)) +
         labs(x='Commune', 
              y='Popoulation') +
         ggtitle(.y) +
    coord_flip()
  )


all_plots <- c()
for (i in 1:80) {
 x <-  (commune_map[[i]] + commune_col[[i]]) / commune_boxwhisker[[i]]
 all_plots[[length(all_plots) + 1]] <- x    # Append new list element
}

```


```{r longlist-generation}
(list.files(here('data', 'input', 'oncho_incidence'), full.names=T, recursive=T) %>%
    keep(~ str_detect(.x, '.xls')) %>%
    map_dfr(~ readxl::read_xls(.x) %>% mutate(province = .x) %>% 
              mutate(province= str_replace(
                province, 
                "/Users/DK_kirby/Library/CloudStorage/OneDrive-UNSW/analysis/angola_oem_iuselect/data/input/oncho_incidence/", 
                "")) %>% 
              clean_names)
     ->
    incidence_raw)

incidence_clean <- incidence_raw %>% 
  mutate(new = coalesce(!!! select(., contains("provincia")))) %>% 
  mutate(municipality=coalesce(organisationunitname, new)) %>% 
  select(-c(organisationunitname, new, contains('provincia'))) %>% 
  filter(!province=='ANUAL-2017.xls') %>% 
  mutate(province= str_replace(
    province, 
    ".xls", 
    "")) %>% 
  clean_data() %>% 
  select(province, municipality, everything()) %>% 
  mutate(province = case_when ( province=="benguela222" ~ 'huila', 
                                 TRUE ~ province)) %>% 
  pivot_longer(
    -c(province, municipality)) %>% 
  mutate(
    year = str_replace(name, 'ne_onconcercose_casos_filariosis_ocular_', '')) %>% 
  mutate(
    municipality = str_replace(municipality, 'municipio_de_', '')) %>%
  mutate(province = case_when(province=='c_norte' ~ 'cuanza_norte', 
                              province=='c_sul' ~ 'cuanza_sul', 
                              province=='l_norte' ~ 'lunda_norte', 
                              
                              TRUE ~ province)) %>% 
  select(-name) 


# Municipality level populations


#https://medium.com/@samukweku/reshaping-an-excel-table-in-r-71d7d9020124

#sourcefile
filename <- here('data/input/Estimativas_Comunais_Geral_Final.xlsx')
#get list of sheet_names
#which also represents the company names
sheet_names <- xlsx_sheet_names(filename)#read in file, using the tidyxl package
#filter for only character and numeric
#and pick specific rows and columns
def <- function(sheetname){xlsx_cells(filename,sheetname)%>%
    filter(data_type %in% c("character","numeric"), 
           row >=5, 
           col >=1)}
#stage1
#apply function to sheetnames
#using the purrr library
stage1 <- map(sheet_names, def)

def_main <- function(datum){datum%>%
    select(sheet,row,col,data_type,character,numeric)%>%
    #behead("NNE",years)%>%
    behead("NNE",commune)%>%
    fill(character, .direction = "down") %>% 
    filter(!is.na(commune))
}#apply function to every tibble in stage1
stage2 <- map(stage1,def_main)

municpality_population <- stage2  %>% 
  bind_rows(.id="province") %>% 
  select(province=sheet, municipality=commune, population=numeric)  %>% 
  filter(!is.na(population)) %>% 
  group_by(province, municipality) %>% 
  slice(which.max(population))  %>% 
  clean_data() %>% 
  filter(!municipality %in% c('talatona')) %>% 
  mutate(municipality= case_when(municipality=='quilombo_dos_dembos' ~ 'gonguembo', 
                                 municipality=='lumbala_nguimbo' ~ 'bundas',
                                 municipality=='muxima' ~ 'quicama',
                                 municipality=='cazombo' ~ 'alto_zambeze',
                                 municipality=='ambaca_ex_camabatela' ~ 'ambaca',
                                 municipality=='ndalatando' ~ 'cazengo',
                                 municipality=='omukolongonjo' ~ 'cuvelai',
                                 municipality=='catete' ~ 'icolo_e_bengo',
                                 municipality=='quinzala' ~ 'mucaba', 
                                 municipality=='benfica' ~ 'talatona', 
                                 
                                 TRUE ~ municipality))


incidence_pop_merge <- incidence_clean %>%   mutate(municipality=case_when(municipality=='ambaca_ex_camabatela' ~ 'ambaca', 
                                                    municipality=='malange' ~ 'malanje', 
                                                    municipality=='tchicala_tcholohanga' ~ 'tchikala_tcholohanga', 
                                                    municipality=='quibala' ~ 'kibala', 
                                                    municipality=='sumbe' ~ 'sumbe_sede', 
                                                    municipality=='belas' ~ 'futungo_de_belas', 
                                                    municipality=='kilamba_kiaxi' ~ 'kilamba', 
                                                    municipality=='kiwaba_nzogi' ~ 'kiwaba_n_zogi',
                                                    municipality=='quirima' ~ 'kirima',
                                                    municipality=='cela' ~ 'cela_ex_waku_kungo',
                                                    municipality=='lumeje_cameia' ~ 'cameia',
                                                    TRUE ~ municipality)) %>% 
  left_join(municpality_population, by=c('province', 'municipality')) %>% 
  filter(!value>1000) %>% 
  mutate(incidence_per100k=(value/population)*100000) %>% 
  mutate(municipality=case_when(municipality== 'cela_ex_waku_kungo' ~ 'cela_waku_kungo', 
                                municipality== 'quicama' ~ 'quissama_muxima_quicama', 
                                municipality== 'kiwaba_n_zogi' ~ 'kiuaba_n_zoji_cuaba_nzogo', 
                                municipality== 'kuimba' ~ 'cuimba', 
                                TRUE ~ municipality))


province_incidence <- incidence_pop_merge %>% 
  group_by(year, province) %>% 
  summarise(province_incidence=sum(value, na.rm=TRUE),
      province_population=sum(population,na.rm=TRUE)) %>% 
  mutate(province_incidence_per100k=(province_incidence/province_population)*100000)

municipality_incidence <- incidence_pop_merge %>% 
  group_by(year, province,municipality) %>% 
  summarise(municipality_incidence=sum(value, na.rm=TRUE),
            municpality_population=sum(population,na.rm=TRUE)) %>% 
  mutate(municipality_incidence_per100k=(municipality_incidence/municpality_population)*100000) 

case_reported <- municipality_incidence %>% 
  filter(municipality_incidence>0) %>% 
  ungroup() %>% 
  distinct(province, municipality) %>% 
  mutate(case_reported='YES')

longlist <- angola_commune_oncho_noloaloa_over71 %>% as_tibble() %>% pull(adm3_pcode)

final_table <- angola_commune_oncho_noloaloa_over71 %>% as_tibble() %>% 
  select(province=adm1_en, municipality=adm2_en, commune=adm3_en, population, Endemicity )

province_final_table <- final_table %>% tabyl(province) %>% 
  adorn_pct_formatting(rounding = "half up", digits = 0) %>% 
  adorn_totals("row")

saveRDS(province_final_table, here('tables','province_final_table.Rds'))


df1 <- angola_commune_oncho_collapse %>% as_tibble() %>% 
  select( "adm1_pcode","adm2_pcode","adm3_pcode","oncho_mean_aw" )

df2 <- angola_commune_oncho_noloaloa_over71 %>% as_tibble() %>% 
  select("adm1_pcode","adm2_pcode","adm3_pcode","adm1_en","adm2_en","adm3_en",propover71,total_pop, Endemicity )

df3 <- neighbour_endemic_area %>% as_tibble() %>% select(adm1_en, adm2_en, adm3_en) %>% mutate(neighbours_endemic_iu='Yes')

commune_survey_data <- readRDS(here('data','output','commune_survey_data.Rds')) %>% 
  group_by(adm1_en, adm2_en, adm3_en) %>% 
  filter(SurveyYear==max(SurveyYear))
        
df2_merge_df3 <- df2 %>% left_join(df3, by=c("adm1_en","adm2_en","adm3_en")) %>% 
  left_join(commune_survey_data, by=c("adm1_en","adm2_en","adm3_en"))

df_merge <- df2_merge_df3 %>% left_join(df1, by=c("adm1_pcode","adm2_pcode","adm3_pcode")) %>% 
  mutate(lf_treatment=case_when(grepl('lf', Endemicity, ignore.case=T) ~ 'Yes')) %>% 
  left_join(case_reported, by=c('adm1_en'='province', 'adm2_en'='municipality')) %>% 
  arrange(adm1_en, adm2_en) %>% 
  mutate(propover71=propover71/100,
         oncho_mean_aw=oncho_mean_aw/100,
         total_pop=total_pop/1000
         )

env_rank_df <- df_merge %>% 
  mutate(env_rank=dense_rank(desc(oncho_mean_aw))) %>% 
  filter(env_rank<=50)
  
prop_rank_df <- df_merge %>% 
  mutate(prop_rank=dense_rank(desc(propover71))) %>% 
  filter(prop_rank<=50)

prev_rank_df <- df_merge %>% 
  filter(Prevalence>0) %>% 
  mutate(prev_rank=dense_rank(desc(Prevalence))) %>% 
  filter(prev_rank<=50)


shortlist <- env_rank_df %>% bind_rows(prop_rank_df,prev_rank_df) %>% 
  count(adm1_en, adm2_en,adm3_en,adm3_pcode) %>% 
  #count(adm1_pcode, adm2_pcode, adm3_pcode) %>% 
  filter(n==3) %>% 
  pull(adm3_pcode)

shortlist_df <- env_rank_df %>% bind_rows(prop_rank_df,prev_rank_df) %>% 
  count(adm1_en, adm2_en) %>% 
  filter(n==3) 
  
saveRDS(shortlist_df, here('maps', 'r_objects', 'shortlist_df.Rds'))


high_ranking_map <- commune_shp %>% 
  mutate(list_cat=case_when((adm3_pcode %in% longlist & !adm3_pcode %in% shortlist)~ "Longlist",
                            adm3_pcode %in% shortlist ~ 'Shortlist')) %>% 
  filter(!is.na(list_cat)) %>% 
  ggplot(data=.) +
  geom_sf(aes(fill=list_cat), size = 0.5, linetype="dotted", size=0.7) +
  # geom_sf(fill = "transparent", color = "dark grey", size = 1.2,
  #         data=iu_shp %>% st_simplify()) +
  geom_sf(fill = "transparent", color = "black", size = 2.5,
          data=adm1_shp %>% st_simplify()) +
  labs(fill='', 
       #title='Identifying priority areas for onchocercisis elimination mapping #in Angola',
       subtitle='Borders: Thick black line = Province, Thin grey line = Municipality, Dashed line = Commune ') +
  theme_minimal() +
  theme(legend.position='top')

saveRDS(high_ranking_map, here('maps', 'r_objects', 'high_ranking_map.Rds'))
high_ranking_map
```



